"""empty message

Revision ID: 73be0659a53f
Revises: 02b61cc82631
Create Date: 2022-03-18 01:32:40.292787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73be0659a53f'
down_revision = '02b61cc82631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('television_series',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('show_title', sa.String(length=150), nullable=True),
    sa.Column('seasons', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('network', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('television_series')
    # ### end Alembic commands ###
