"""empty message

Revision ID: ee7d6260991b
Revises: 73be0659a53f
Create Date: 2022-03-18 04:04:34.239212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7d6260991b'
down_revision = '73be0659a53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'television_series', ['show_title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'television_series', type_='unique')
    # ### end Alembic commands ###
